name: Build

on:
  push:
    branches-ignore:
    - gh-pages
  pull_request:
    branches-ignore:
    - gh-pages
  release:
    branches-ignore:
    - gh-pages

jobs:
  build-windows:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin

    - name: Build
      run: make

    - name: Upload jar
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jar-windows
        path: _build/main/io.github.btj.termios.jar
        if-no-files-found: error

  build-macos:
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin

    - name: Build
      run: make

    - name: Upload jar
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jar-macos
        path: _build/main/io.github.btj.termios.jar
        if-no-files-found: error

  build-ubuntu:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin

    - name: Build
      run: make && make javadoc

    - name: Upload jar
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jar-ubuntu
        path: _build/main/io.github.btj.termios.jar
        if-no-files-found: error
        
    - name: Upload docs
      uses: actions/upload-artifact@v4.3.1
      with:
        name: docs
        path: _build/docs
        if-no-files-found: error

  build-multiplatform-jar:
    runs-on: ubuntu-latest
    needs:
    - build-windows
    - build-macos
    - build-ubuntu

    steps:
    - name: Setup Java JDK
      uses: actions/setup-java@v4.0.0
      with:
        java-version: 21
        distribution: temurin

    - name: Download artifacts
      uses: actions/download-artifact@v4.1.2

    - name: Bundle jars
      run: |
        mkdir classes
        cd classes
        jar xf ../jar-ubuntu/io.github.btj.termios.jar
        jar xf ../jar-macos/io.github.btj.termios.jar
        jar xf ../jar-windows/io.github.btj.termios.jar
        cd ..
        jar cf io.github.btj.termios.jar -C classes .

    - name: Upload jar
      uses: actions/upload-artifact@v4.3.1
      with:
        name: jar-multiplatform
        path: io.github.btj.termios.jar
        if-no-files-found: error

    - name: Upload multiplatform jar and docs as release asset
      if: github.repository == 'btj/termios' && github.event_name == 'release'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        mv io.github.btj.termios.jar io.github.btj.termios-$GITHUB_REF_NAME.jar
        gh release upload $GITHUB_REF_NAME io.github.btj.termios-$GITHUB_REF_NAME.jar --clobber --repo btj/termios
        pushd docs && zip -r ../io.github.btj.termios-$GITHUB_REF_NAME-docs.zip . && popd
        gh release upload $GITHUB_REF_NAME io.github.btj.termios-$GITHUB_REF_NAME-docs.zip --clobber --repo btj/termios

    - name: Push docs to gh-pages branch
      if: github.repository == 'btj/termios' && github.event_name == 'release'
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      run: |
        git clone -b gh-pages $GITHUB_SERVER_URL/$GITHUB_REPOSITORY gh-pages
        cd gh-pages/docs
        cp -R ../../docs $GITHUB_REF_NAME
        echo '<a href="'$GITHUB_REF_NAME'">'$GITHUB_REF_NAME'</a>' >> index.html
        git config --global user.name "$GITHUB_REPOSITORY GitHub Actions runner"
        git config --global user.email "no@email"
        git add .
        git commit -m "Add release $GITHUB_REF_NAME docs (built from $GITHUB_SHA)"
        gh auth setup-git
        git push origin gh-pages
